# GitHub Actions 工作流名称
name: 'Auto Tennis Court Booking'

on:
  # 1. 定时触发：使用 CRON 表达式
  #    CRON 时间是 UTC 时间，'28 0 * * *' 对应 UTC 时间的 00:28。
  #    这比北京时间 (UTC+8) 的 08:28 早 8 小时。
  #    所以在北京时间每天早上 08:28，此工作流会自动运行。
  schedule:
    - cron: '28 0 * * *'

  # 2. 手动触发：允许你在 GitHub 的 Actions 页面手动点击运行
  workflow_dispatch:

jobs:
  run-booking-script:
    # 使用最新的 Ubuntu 虚拟环境
    runs-on: ubuntu-latest

    steps:
      # 第一步：检出你的代码
      # 这会将你的 booking.py 脚本下载到虚拟环境中
      - name: 'Checkout repository'
        uses: actions/checkout@v4

      # 第二步：设置 Python 环境
      - name: 'Set up Python'
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # 你可以根据需要选择 Python 版本

      # 第三步：安装 Playwright 及其依赖
      - name: 'Install Playwright dependencies'
        run: |
          pip install playwright
          # 安装 playwright 所需的浏览器和操作系统依赖
          playwright install --with-deps
      
      # 第四步：运行你的预约脚本
      - name: 'Run booking script'
        # 在这里，我们通过 env 将 GitHub Secrets 注入到脚本的环境变量中
        # 你的 Python 脚本中的 os.getenv() 将会读取到这些值
        env:
          BOOKING_USERNAME: ${{ secrets.BOOKING_USERNAME }}
          BOOKING_PASSWORD: ${{ secrets.BOOKING_PASSWORD }}
          # 这个环境变量是脚本用来判断是否在 CI 环境下运行的
          GITHUB_ACTIONS: 'true'
        run: python booking.py
